from .envs import *

__all__ = [
    "CAMERA_0_DEVICE",
    "CAMERA_0_NAME",
    "CAMERA_1_DEVICE",
    "CAMERA_1_NAME",
    "CAMERA_DEFAULT_RESOLUTION",
    "CAMERA_DEFAULT_FPS",
    "CAMERA_DEFAULT_CODEC",
    "FEED_OUTPUT_DIR",
    "FEED_OUTPUT_NAME",
    "FEED_OUTPUT_FORMAT",
    "FEED_OUTPUT_CODEC",
    "FEED_OUTPUT_BITRATE",
    "FEED_OUTPUT_FPS",
    "FEED_OUTPUT_RESOLUTION"
]
