CAMERA_0_NAME = "Left Camera"
CAMERA_0_INDEX = 0
CAMERA_1_NAME = "Right Camera"
CAMERA_1_INDEX = 1
CAMERA_DEFAULT_RESOLUTION = (2304, 1296)
CAMERA_DEFAULT_FPS = 56
CAMERA_DEFAULT_CODEC = "yuv420"


FEED_OUTPUT_DIR = "/var/lib/strixcam/capture/feeds"
FEED_OUTPUT_NAME = "CombinedFeed"
FEED_OUTPUT_FORMAT = ""
FEED_OUTPUT_CODEC = ""
FEED_OUTPUT_BITRATE = ""
FEED_OUTPUT_FPS = 60
FEED_OUTPUT_RESOLUTION = (3840, 1080)
