CAMERA_0_DEVICE = "/dev/video0"
CAMERA_0_NAME = "Left Camera"
CAMERA_1_DEVICE = "/dev/video1"
CAMERA_1_NAME = "Right Camera"
CAMERA_DEFAULT_RESOLUTION = (1920, 1080)
CAMERA_DEFAULT_FPS = 30
CAMERA_DEFAULT_CODEC = "yuv420"


FEED_OUTPUT_DIR = "/var/lib/strixcam/capture/feeds"
FEED_OUTPUT_NAME = "CombinedFeed"
FEED_OUTPUT_FORMAT = ""
FEED_OUTPUT_CODEC = ""
FEED_OUTPUT_BITRATE = ""
FEED_OUTPUT_FPS = 30
FEED_OUTPUT_RESOLUTION = (3840, 1080)
